# Generated by Django 2.0 on 2017-12-28 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='ower',
            field=models.ForeignKey(default=1, on_delete=1, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
